# Generated by Django 4.1 on 2022-08-31 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrcnHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_product_name', models.TextField(default='')),
                ('h_amount', models.FloatField()),
                ('facture_file', models.FileField(upload_to='factures/')),
                ('h_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('h_trcn_frm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='h_trcn_frm', to=settings.AUTH_USER_MODEL)),
                ('h_trcn_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
